18-349 Kernel: gpio.c File Reference
gpio.c File Reference
Lower level definitions for accessing gpio on raspberry pi.
#include <arm.h>
#include <kstdint.h>
#include <BCM2836.h>
Macros
#define MMIO_BASE_PHYSICAL 0x3F000000
#define GPIO_BASE (MMIO_BASE_PHYSICAL + 0x200000)
base of GPIO in memory mapped IO on pi see page 89 onward in BCM2835 peripherals for info about MMIO for GPIO
#define GPIO_REG_GPFSEL0 0
GPIO Function Select 0.
#define GPIO_REG_GPFSEL1 1
GPIO Function Select 1.
#define GPIO_REG_GPFSEL2 2
GPIO Function Select 2.
#define GPIO_REG_GPFSEL3 3
GPIO Function Select 3.
#define GPIO_REG_GPFSEL4 4
GPIO Function Select 4.
#define GPIO_REG_GPFSEL5 5
GPIO Function Select 5.
#define GPIO_REG_GPSET0 7
GPIO Pin Output Set 0.
#define GPIO_REG_GPSET1 8
GPIO Pin Output Set 1.
#define GPIO_REG_GPCLR0 10
GPIO Pin Output Clear 0.
#define GPIO_REG_GPCLR1 11
GPIO Pin Output Clear 1.
#define GPIO_REG_GPLEV0 13
GPIO Pin Level 0.
#define GPIO_REG_GPLEV1 14
GPIO Pin Level 1.
#define GPIO_REG_GPEDS0 16
GPIO Pin Event Detect Status 0.
#define GPIO_REG_GPEDS1 17
GPIO Pin Event Detect Status 1.
#define GPIO_REG_GPREN0 19
GPIO Pin Rising Edge Detect Enable 0.
#define GPIO_REG_GPREN1 20
GPIO Pin Rising Edge Detect Enable 1.
#define GPIO_REG_GPFEN0 22
GPIO Pin Falling Edge Detect Enable 0.
#define GPIO_REG_GPFEN1 23
GPIO Pin Falling Edge Detect Enable 1.
#define GPIO_REG_GPHEN0 25
GPIO Pin High Detect Enable 0.
#define GPIO_REG_GPHEN1 26
GPIO Pin High Detect Enable 1.
#define GPIO_REG_GPLEN0 28
GPIO Pin Low Detect Enable 0.
#define GPIO_REG_GPLEN1 29
GPIO Pin Low Detect Enable 1.
#define GPIO_REG_GPAREN0 31
GPIO Pin Async. Rising Edge Detect 0.
#define GPIO_REG_GPAREN1 32
GPIO Pin Async. Rising Edge Detect 1.
#define GPIO_REG_GPAFEN0 34
GPIO Pin Async. Falling Edge Detect 0.
#define GPIO_REG_GPAFEN1 35
GPIO Pin Async. Falling Edge Detect 1.
#define GPIO_REG_GPPUD 37
GPIO Pin Pull-up/down Enable.
#define GPIO_REG_GPPUDCLK0 38
GPIO Pin Pull-up/down Enable Clock 0.
#define GPIO_REG_GPPUDCLK1 39
GPIO Pin Pull-up/down Enable Clock 1.
Functions
void gpio_config (uint8_t pin, uint8_t fun)
configures a pin for a given functionality.
void gpio_set (uint8_t pin)
sets a given GPIO pin high.
void gpio_clr (uint8_t pin)
sets a given GPIO pin low.
void gpio_set_pull (uint8_t pin, uint8_t state)
configures a given pin to be pulled high, low or have pull up/down disabled.
Variables
static volatile uint32_t * gpio = (volatile uint32_t*)GPIO_BASE
GPIO register set.
Detailed Description
Lower level definitions for accessing gpio on raspberry pi.
Date
July 15 2015
Author
Aaron Reyes areye.nosp@m.s@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Function Documentation
void gpio_clr (uint8_t pin)
sets a given GPIO pin low.
Parameters
pin the pin number to clear (0 to 53 on pi)
References gpio, GPIO_REG_GPCLR0, and GPIO_REG_GPCLR1.
Referenced by led_clr_green(), and led_clr_red().
void gpio_config (uint8_t pin, uint8_t fun)
configures a pin for a given functionality.
See BCM2835 peripherals pg 102 - 103 for various alternate functions of GPIO pins.
Parameters
pin the pin number to configure (0 to 53 on pi)
fun the function type (see defines)
References gpio.
Referenced by i2c_master_init(), led_init(), spi_master_init(), and uart_init().
void gpio_set (uint8_t pin)
sets a given GPIO pin high.
Parameters
pin the pin number to set (0 to 53 on pi)
References gpio, GPIO_REG_GPSET0, and GPIO_REG_GPSET1.
Referenced by led_set_green(), and led_set_red().
void gpio_set_pull (uint8_t pin, uint8_t state)
configures a given pin to be pulled high, low or have pull up/down disabled.
Parameters
pin the pin number to configure (0 to 53 on pi)
state should be GPIO_PULL_* from defines.
References delay_cycles(), gpio, GPIO_REG_GPPUD, GPIO_REG_GPPUDCLK0, and GPIO_REG_GPPUDCLK1.
Referenced by i2c_master_init(), and uart_init().