18-349 Kernel: gpio.h File Reference
gpio.h File Reference
Lower level definitions for accessing gpio on raspberry pi.
#include <kstdint.h>
Macros
#define GPIO_FUN_INPUT 0
GPIO Function Select INPUT.
#define GPIO_FUN_OUTPUT 1
GPIO Function Select OUTPUT.
#define GPIO_FUN_ALT0 4
GPIO Function Select 0.
#define GPIO_FUN_ALT1 5
GPIO Function Select 1.
#define GPIO_FUN_ALT2 6
GPIO Function Select 2.
#define GPIO_FUN_ALT3 7
GPIO Function Select 3.
#define GPIO_FUN_ALT4 3
GPIO Function Select 4.
#define GPIO_FUN_ALT5 2
GPIO Function Select 5.
#define GPIO_PULL_UP 2
GPIO pull up.
#define GPIO_PULL_DOWN 1
GPIO pull down.
#define GPIO_PULL_DISABLE 0
GPIO pull disable.
Functions
void gpio_config (uint8_t pin, uint8_t fun)
configures a pin for a given functionality.
void gpio_set (uint8_t pin)
sets a given GPIO pin high.
void gpio_clr (uint8_t pin)
sets a given GPIO pin low.
void gpio_set_pull (uint8_t pin, uint8_t state)
configures a given pin to be pulled high, low or have pull up/down disabled.
Detailed Description
Lower level definitions for accessing gpio on raspberry pi.
Date
July 15 2015
Author
Aaron Reyes areye.nosp@m.s@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Function Documentation
void gpio_clr (uint8_t pin)
sets a given GPIO pin low.
Parameters
pin the pin number to clear (0 to 53 on pi)
References gpio, GPIO_REG_GPCLR0, and GPIO_REG_GPCLR1.
Referenced by led_clr_green(), and led_clr_red().
void gpio_config (uint8_t pin, uint8_t fun)
configures a pin for a given functionality.
See BCM2835 peripherals pg 102 - 103 for various alternate functions of GPIO pins.
Parameters
pin the pin number to configure (0 to 53 on pi)
fun the function type (see defines)
References gpio.
Referenced by i2c_master_init(), led_init(), spi_master_init(), and uart_init().
void gpio_set (uint8_t pin)
sets a given GPIO pin high.
Parameters
pin the pin number to set (0 to 53 on pi)
References gpio, GPIO_REG_GPSET0, and GPIO_REG_GPSET1.
Referenced by led_set_green(), and led_set_red().
void gpio_set_pull (uint8_t pin, uint8_t state)
configures a given pin to be pulled high, low or have pull up/down disabled.
Parameters
pin the pin number to configure (0 to 53 on pi)
state should be GPIO_PULL_* from defines.
References delay_cycles(), gpio, GPIO_REG_GPPUD, GPIO_REG_GPPUDCLK0, and GPIO_REG_GPPUDCLK1.
Referenced by i2c_master_init(), and uart_init().