18-349 Kernel: i2c.c File Reference
i2c.c File Reference
I2C implementation on rpi 2.
#include <kstdint.h>
#include <BCM2836.h>
#include <gpio.h>
#include <i2c.h>
#include <printk.h>
Functions
void i2c_master_init (uint16_t clk)
initializes the I2C module
uint8_t i2c_master_write (uint8_t *buf, uint16_t len, uint8_t addr)
Algorithm: Clear off previously set flags, set the values of the DLEN and Address registers and set the start bit to 1. Wait for the transfer process to become active (TA). Once the transfer is active, check if the FIFO can accept data (TXD) and keep writing to the FIFO until the whole data has been written. If the FIFO gets filled, wait for it to be able to start accepting data again. If acknowledgement errors are encountered, the write process is terminated and 0 is returned.
uint8_t i2c_master_read (uint8_t *buf, uint16_t len, uint8_t addr)
Algorithm: Clear off previously set flags, set the DLEN and Address registers, Set the start bit to 1 and wait for the data to get populated in the FIFO (RXD). Check for the errors in acknowledgement while waiting. If an acknowledgement error is encountered, the read process is terminated and the value returned is 0. Once the data is availablein the FIFO register (RXD), read it byte by byte and copy it to the location pointed by 'buf'.
Detailed Description
I2C implementation on rpi 2.
Date
03 Oct 2016
Author
Rishabh Bhatnagar risha.nosp@m.bhb@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Krishanu Ganguly krish.nosp@m.ang@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
void i2c_master_init (uint16_t clk)
initializes the I2C module
Parameters
clk bus clock speed in KHz
References gpio_config(), GPIO_FUN_ALT0, GPIO_PULL_UP, and gpio_set_pull().
uint8_t i2c_master_read (uint8_t * buf, uint16_t len, uint8_t addr)
Algorithm: Clear off previously set flags, set the DLEN and Address registers, Set the start bit to 1 and wait for the data to get populated in the FIFO (RXD). Check for the errors in acknowledgement while waiting. If an acknowledgement error is encountered, the read process is terminated and the value returned is 0. Once the data is availablein the FIFO register (RXD), read it byte by byte and copy it to the location pointed by 'buf'.
reads from I2C device
Parameters
*buf Pointer to the memory location where the read values would be stored.
len Length of data to be read.
addr Address of I2C device.
Returns
0: Read Failure 1: Read Successful
Referenced by adc_read().
uint8_t i2c_master_write (uint8_t * buf, uint16_t len, uint8_t addr)
Algorithm: Clear off previously set flags, set the values of the DLEN and Address registers and set the start bit to 1. Wait for the transfer process to become active (TA). Once the transfer is active, check if the FIFO can accept data (TXD) and keep writing to the FIFO until the whole data has been written. If the FIFO gets filled, wait for it to be able to start accepting data again. If acknowledgement errors are encountered, the write process is terminated and 0 is returned.
writes to I2C device
Parameters
*buf Pointer to the memory location from which the values would be written.
len Length of data to be written.
addr Address of I2C device.
Returns
0: Write Failure 1: Write Successful
Referenced by adc_read().