18-349 Kernel: printk.c File Reference
printk.c File Reference
printf() implementation for KERNEL using UART
#include <kstdint.h>
#include <kstdarg.h>
#include <uart.h>
Macros
#define MAXBUF (sizeof(uint64_t))
Functions
static void printnumk (uint8_t base, uint64_t num)
prints a number
int printk (const char *fmt,...)
A kernel printf() function for debugging the kernel.
Variables
static char digits [] = "0123456789abcdef"
Detailed Description
printf() implementation for KERNEL using UART
Date
July 27 2015
Author
Aaron Reyes areye.nosp@m.s@an.nosp@m.drew..nosp@m.cmu..nosp@m.edu
Macro Definition Documentation
#define MAXBUF (sizeof(uint64_t))
allows for numbers with 64 digits/letters
Referenced by printnumk().
Function Documentation
int printk (const char * fmt, ...)
A kernel printf() function for debugging the kernel.
Parameters
fmt the format string
Returns
0 on success or -1 on failure
References printnumk(), and uart_put_byte().
Referenced by irq_c_handler(), syscall_exit(), and syscall_read().
static void printnumk (uint8_t base, uint64_t num) static
prints a number
Parameters
base 8, 10, 16
num the number to print
References digits, MAXBUF, and uart_put_byte().
Referenced by printk().
Variable Documentation
char digits[] = "0123456789abcdef" static
static array of digits for use in printnum(s)
Referenced by printnumk().