18-349 Kernel: syscalls.h File Reference
syscalls.h File Reference
Syscall handlers, used by kernel's SWI handler.
#include <kstdint.h>
Functions
void * syscall_sbrk (int incr)
See linux man page for sbrk.
int syscall_write (int file, char *ptr, int len)
See linux man page for write.
int syscall_close (int file)
See linux man page for close. Since we only read/write to stdin/stdout, close doesn't really do anything.
int syscall_fstat (int file, void *st)
See linux man page for fstat. Since we don't have a file system, this doesn't actually do anything.
int syscall_isatty (int file)
See linux man page for isatty. Our implementation always returns TRUE since we only use stdin and stdout.
int syscall_lseek (int file, int offset, int whence)
See linux man page for lseek. Not implemented in our kernel since we don't have a filesystem.
int syscall_read (int file, char *ptr, int len)
See linux man page for read.
void syscall_exit (int status)
Print out the exit status of the user program and hang with interrupts disabled (this is different behavior than the Linux man pages!)
int syscall_sample_adc_start (int freq, uint8_t channel, void(*callback)(uint16_t))
Starts sampling the ADC periodically, calling the given callback with the ADC sample value.
int syscall_sample_adc_stop ()
Stops periodic sampling of the ADC.
Detailed Description
Syscall handlers, used by kernel's SWI handler.
Date
September 26, 2015
Author
Kenneth Li kyli@.nosp@m.andr.nosp@m.ew.cm.nosp@m.u.ed.nosp@m.u
Function Documentation
int syscall_close (int file)
See linux man page for close. Since we only read/write to stdin/stdout, close doesn't really do anything.
Parameters
file file descriptor to close.
Returns
-1 on error, 0 on success.
void syscall_exit (int status)
Print out the exit status of the user program and hang with interrupts disabled (this is different behavior than the Linux man pages!)
Parameters
status Exit status to return to the kernel
References hang(), and printk().
Referenced by swi_c_handler().
int syscall_fstat (int file, void * st)
See linux man page for fstat. Since we don't have a file system, this doesn't actually do anything.
Parameters
file file descriptor to examine
st pointer to stat structure
Returns
-1 on error, 0 on success
Referenced by swi_c_handler().
int syscall_isatty (int file)
See linux man page for isatty. Our implementation always returns TRUE since we only use stdin and stdout.
Parameters
file file descriptor to check.
Returns
boolean (1 or 0) indicating whether the fd is a tty
int syscall_lseek (int file, int offset, int whence)
See linux man page for lseek. Not implemented in our kernel since we don't have a filesystem.
Parameters
file file descriptor
offset offset
whence see man page for appropriate values
Returns
-1 on error, 0 on success
int syscall_read (int file, char * ptr, int len)
See linux man page for read.
Parameters
file file descriptor to read from. In our kernel, we only support STDIN.
ptr pointer to buffer to read from
len max length to read
Returns
-1 on error, otherwise number of bytes read
Reads until all len bytes are read or newline/return is found. Detects backspace and EOL characters and handles them appropriately.
The idea is to mimic normal terminal reading input, that is, if the user hits backspace it should erase the previously read character.
References printk(), uart_get_byte(), and uart_put_byte().
Referenced by swi_c_handler().
int syscall_sample_adc_start (int freq, uint8_t channel, void(*)(uint16_t) callback)
Starts sampling the ADC periodically, calling the given callback with the ADC sample value.
Parameters
freq frequency at which to sample
channel channel to sample
callback function to be called everytime a sample is read from the adc.
Returns
0 on success or -1 on failure
References gl, and timer_start().
Referenced by swi_c_handler().
int syscall_sample_adc_stop ()
Stops periodic sampling of the ADC.
Returns
0 on success or -1 on failure
References timer_stop().
Referenced by swi_c_handler().
void* syscall_sbrk (int incr)
See linux man page for sbrk.
Parameters
incr amount to increment data segment size by.
Returns
-1 if error, or the previous end address of the heap
References heap_end.
Referenced by swi_c_handler().
int syscall_write (int file, char * ptr, int len)
See linux man page for write.
Parameters
file file descriptor to write to. In our kernel, we only support STDOUT.
ptr pointer to buffer to write to
len max length to write
Returns
-1 on error, otherwise the number of bytes written
References uart_put_byte().
Referenced by swi_c_handler().