18-349 Kernel: Thread.c File Reference
Thread.c File Reference
interface for system calls pertaining to threads and context switching
#include <Thread.h>
#include <timer.h>
#include <screen.h>
#include <printk.h>
#include <mutex_type.h>
#include <arm.h>
Macros
#define SVC_STACK_SIZE 1024
#define REFRESH_PERIOD 1024
#define BUFFER_SIZE 128
Functions
void start_thread (thread_fn fn, uint32_t *s)
void threads_init ()
thread_fn get_idle_thread ()
int syscall_thread_init (thread_fn idle_fn, uint32_t *idle_stack_start)
Initialize the thread library.
int syscall_thread_create (thread_fn fn, uint32_t *stack_start, unsigned int prio, unsigned int C, unsigned int T)
Create a new thread running the given function.
int syscall_mutex_init (mutex_t *mutex, unsigned int max_prio)
Initialize the mutex.
void syscall_mutex_lock (mutex_t *mutex)
Lock the mutex.
void syscall_mutex_unlock (mutex_t *mutex)
Unlock the mutex.
int getMostImportantRunnableThread ()
Returns the index of the most important thread at the given point in time.
volatile TCB * context_switch ()
Returns the TCB of the new task to be loaded.
int check_time ()
This is called every IRQ interrupt.
uint32_t * get_svc_sp ()
Returns the kernel SP of the presently running thread.
int save_context (int *context)
void save_context_SVC (uint32_t *LR_svc, uint32_t *SP_svc, uint32_t SPSR_svc)
Routine to back up the kernel LR, SPSR and SP registers for the current running in the event of a SWI.
void save_context_user (uint32_t *LR, uint32_t *SP)
Routine to back up the user-space LR and SP registers in the event of an interrupt.
void save_context_irq (int *context)
Routine to back up all the registers in the event of an IRQ interrupt.
void syscall_wait_until_next_period ()
Efficiently waits to run until the next period.
unsigned int syscall_get_time (void)
Get the current time in milliseconds.
int syscall_scheduler_start (void)
Allow the kernel to start running the added task set.
int UB_Test (void)
Carry out the UB test before scheduling a set of tasks.
void set_UB_Bounds (void)
Sets the utilization bounds for tasks.
Variables
uint32_t idle_svc_stack [SVC_STACK_SIZE]
uint32_t thread0_svc_stack [SVC_STACK_SIZE]
uint32_t thread1_svc_stack [SVC_STACK_SIZE]
uint32_t thread2_svc_stack [SVC_STACK_SIZE]
uint32_t thread3_svc_stack [SVC_STACK_SIZE]
uint32_t thread4_svc_stack [SVC_STACK_SIZE]
uint32_t thread5_svc_stack [SVC_STACK_SIZE]
uint32_t thread6_svc_stack [SVC_STACK_SIZE]
uint32_t thread7_svc_stack [SVC_STACK_SIZE]
uint32_t thread8_svc_stack [SVC_STACK_SIZE]
uint32_t thread9_svc_stack [SVC_STACK_SIZE]
uint32_t thread10_svc_stack [SVC_STACK_SIZE]
uint32_t thread11_svc_stack [SVC_STACK_SIZE]
uint32_t thread12_svc_stack [SVC_STACK_SIZE]
uint32_t thread13_svc_stack [SVC_STACK_SIZE]
uint32_t thread14_svc_stack [SVC_STACK_SIZE]
uint32_t thread15_svc_stack [SVC_STACK_SIZE]
uint32_t thread16_svc_stack [SVC_STACK_SIZE]
uint32_t thread17_svc_stack [SVC_STACK_SIZE]
uint32_t thread18_svc_stack [SVC_STACK_SIZE]
uint32_t thread19_svc_stack [SVC_STACK_SIZE]
uint32_t thread20_svc_stack [SVC_STACK_SIZE]
uint32_t thread21_svc_stack [SVC_STACK_SIZE]
uint32_t thread22_svc_stack [SVC_STACK_SIZE]
uint32_t thread23_svc_stack [SVC_STACK_SIZE]
uint32_t thread24_svc_stack [SVC_STACK_SIZE]
uint32_t thread25_svc_stack [SVC_STACK_SIZE]
uint32_t thread26_svc_stack [SVC_STACK_SIZE]
uint32_t thread27_svc_stack [SVC_STACK_SIZE]
uint32_t thread28_svc_stack [SVC_STACK_SIZE]
uint32_t thread29_svc_stack [SVC_STACK_SIZE]
uint32_t thread30_svc_stack [SVC_STACK_SIZE]
volatile unsigned int CLOCK_TICKS
volatile TCB threads [32]
void(* idle_function)(void)
volatile uint32_t waiting_list
volatile uint32_t runnable
volatile int present_thread = 31
int thread_count
float UB_Bounds [STACK_LIMIT]
Detailed Description
interface for system calls pertaining to threads and context switching
Date
15 Nov 2016
Author
Rishabh Bhatnagar risha.nosp@m.bhb@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Krishanu Ganguly krish.nosp@m.ang@.nosp@m.andre.nosp@m.w.cm.nosp@m.u.edu
Function Documentation
int check_time ()
This is called every IRQ interrupt.
It checks the status of the all the threads. Wakes up any waiting thread that ought to be scheduled and determines if a context switch must be performed in that IRQ
Returns
1 for context switch or 0 to return to presently running task
References getMostImportantRunnableThread(), and timer_clear_pending().
volatile TCB* context_switch ()
Returns the TCB of the new task to be loaded.
Returns
The TCB of the new task to be loaded
References getMostImportantRunnableThread().
uint32_t* get_svc_sp ()
Returns the kernel SP of the presently running thread.
Returns
kernel SP of the present task if it hadn't been copied before. Else 0.
int getMostImportantRunnableThread ()
Returns the index of the most important thread at the given point in time.
Returns
The index of the most important thread at the given point in time
Referenced by check_time(), and context_switch().
void save_context_irq (int * context)
Routine to back up all the registers in the event of an IRQ interrupt.
void save_context_SVC (uint32_t * LR_svc, uint32_t * SP_svc, uint32_t SPSR_svc)
Routine to back up the kernel LR, SPSR and SP registers for the current running in the event of a SWI.
void save_context_user (uint32_t * LR, uint32_t * SP)
Routine to back up the user-space LR and SP registers in the event of an interrupt.
void set_UB_Bounds (void)
Sets the utilization bounds for tasks.
Referenced by syscall_thread_init().
int syscall_mutex_init (mutex_t * mutex, unsigned int max_prio)
Initialize the mutex.
A user program must call this initializer before attempting to lock or unlock the mutex. You can assume that this initializer will only be called once by any test programs.
Parameters
mutex The mutex to act on.
max_prio The maximum priority of a thread which could use
Returns
0 on success or -1 on failure
References NULL.
Referenced by swi_c_handler().
void syscall_mutex_lock (mutex_t * mutex)
Lock the mutex.
This function will not return (may block) until the current thread has exclusive rights to the mutex. You can assume the mutex has been initialized.
Parameters
mutex The mutex to act on.
References disable_interrupts(), and enable_interrupts().
Referenced by swi_c_handler().
void syscall_mutex_unlock (mutex_t * mutex)
Unlock the mutex.
Parameters
mutex The mutex to act on.
Referenced by swi_c_handler().
int syscall_scheduler_start (void)
Allow the kernel to start running the added task set.
This function should enable IRQs and thus enable your scheduler. The kernel will test that a task set with this new task is scheduleable before running and may return an error if this is not the case.
Returns
0 on success or -1 on failure
References timer_clear_pending(), timer_start(), and UB_Test().
Referenced by swi_c_handler().
int syscall_thread_create (thread_fn fn, uint32_t * stack_start, unsigned int prio, unsigned int C, unsigned int T)
Create a new thread running the given function.
Parameters
fn Pointer to the function to run in the new thread.
stack_start Pointer to the first valid location of this thread's stack.
prio Priority of this thread. Lower number are higher priority.
C Real time execution time (ms).
T Real time task period (ms).
Returns
0 on success or -1 on failure
Referenced by swi_c_handler().
int syscall_thread_init (thread_fn idle_fn, uint32_t * idle_stack_start)
Initialize the thread library.
A user program must call this initializer before attempting to create any threads or start the scheduler.
Parameters
idle_fn Pointer to a thread function to run when no other threads are runnable.
idle_stack_start Pointer to the first valid location of idle thread's stack.
Returns
0 on success or -1 on failure
References set_UB_Bounds().
Referenced by swi_c_handler().
int UB_Test (void)
Carry out the UB test before scheduling a set of tasks.
This function looks at the threads which are created and carries out a UB Test on the given threads before scheduling them. It compares the utilization against pre-determined values of utilization bounds
Returns
1 on success or 0 on failure
Referenced by syscall_scheduler_start().